# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learn
email: ragakoshceo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this series of blog post, we are going to share the knowledge of Indian Classical Music
  in various methods. We will share unique ragas, videos, podcasts and lots of other stuff.
  Stay Tuned.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://learn.ragakosh.com" # the base hostname & protocol for your site
twitter_username: ragakosh

# Build settings
markdown: kramdown
